### ISSUE TITLE
Limit parameter mistyped

### ISSUE THREAD

**Issue by miljanrajkovic** [JKorf/Bitfinex.Net#42]
I fond several methods in code where limit parameter was typed as "len": GetOrderBookAsync, GetOrderHistoryAsync, GetTradeHistoryAsync, GetFundingOfferHistoryAsync, GetFundingLoansHistoryAsync, GetFundingCreditsHistoryAsyncTask and GetFundingTradesHistoryAsync.
Because of that every call returns default number of records.

parameters.AddOptionalParameter("len", limit?.ToString());

Should be "limit".

**Comment by JKorf** [comment]
Hi, thanks for the report. Should be fixed in the latest version (v1.0.19)!

**Comment by miljanrajkovic** [comment]
Looks better now, but you missed to correct that in the method GetOrderBookAsync.

**Comment by JKorf** [comment]
The API documentation actually states that that parameter is called `len`. I've verified that the parameter works. You can either pass in 25 or 100 which will respectively return 25 and 100 records for each side resulting in array lengths of 50 and 200 records.

**Comment by miljanrajkovic** [comment]
Yes. You are right. That is a call from public API. My mistake.
