### ISSUE TITLE
WS PlaceOrder places orders, but return "{3: Server error: No response on query received }"

### ISSUE THREAD

**Issue by SergeevGregory** [JKorf/Bitfinex.Net#99]
Dear developer,
I try to post order via WS. My code:
`
var bf_ws_client = new Bitfinex.Net.BitfinexSocketClient(new Bitfinex.Net.Objects.BitfinexSocketClientOptions() { ApiCredentials = new CryptoExchange.Net.Authentication.ApiCredentials("***", "***") });

var req_res = bf_ws_client.PlaceOrder (Bitfinex.Net.Objects.OrderType.ExchangeLimit, "tLTCBTC", 0.06m, price: 0.001m);`

Order placed successful, but PlaceOrder return "{3: Server error: No response on query received }".
Can you help me solve this issue?

**Comment by JKorf** [comment]
Hi, it seems that the Bitfinex socket API changed slightly, it's not sending the same event it used to. Can't find any info on that change though. Anyway, I've pushed a new version which should be available in a few minutes.

**Comment by SergeevGregory** [comment]
Dear developer,
please, fix also problem with Getting order book of duskbtc symbol. 

Symbol of this pair can't pass check.

**Comment by FlashPlayer13** [comment]
Hi,

I'm still facing this type of problem. For some reason order canceling operation may return "No response on query received" after 10 seconds of waiting.
Also when (right after) this happens - looks like there is some kind of auto socket restart, because all orderbooks resend full state, like if i subscribed on them first time.
Also when this happens, if i have some orders on fly to server, it can stuck on socketClient.CancelOrder method without any return forever.
So lot of strange things happenning.

I am working with last available version.
